version: '3.3'
services:
  nextcloud:
    container_name: nextcloud
    image: nextcloud
    restart: unless-stopped
    environment:
      - MYSQL_DATABASE=${NC_DB}
      - MYSQL_USER=${NC_DB_USER}
      - MYSQL_PASSWORD=${NC_DB_PWD}
      - MYSQL_HOST=db
      - NEXTCLOUD_ADMIN_USER=${NC_ADMIN}
      - 'NEXTCLOUD_ADMIN_PASSWORD=${NC_ADMIN_PWD}'
      - REDIS_HOST=redis
      - 'NEXTCLOUD_TRUSTED_DOMAINS=${NC_DOMAINS}'
      - 'OVERWRITEPROTOCOL=${NC_ROTOCOL}'
      - 'OVERWRITECLIURL=${NC_URI}'
      - REDIS_PORT=6379
      - 'REDIS_HOST_PASSWORD=${NC_DB_PWD}'
    ports:
      - '5080:80'
    links:
      - db
      - redis
    depends_on:
      - db
      - redis
    volumes:
      - './media/ncconfigs/data:/var/www/html'
      - './media/ncdata/external_data1:/mnt/data_main1'
      - './media/ncdata/external_data2:/mnt/data_main2'
      
  onlyoffice:
    container_name: onlyoffice
    image: onlyoffice/documentserver:latest
    restart: unless-stopped
    environment:
      - 'JWT_ENABLED=true'
      - 'JWT_SECRET=${JWT_KEY}'
      - REDIS_SERVER_HOST=redis
      - REDIS_SERVER_PORT=6379
      - TZ=Asia/Taipei
    ports:
      - '5079:80'
    volumes:
      - ./onlyoffice/logs:/var/log/onlyoffice
      - ./onlyoffice/data:/var/www/onlyoffice/Data
      - ./onlyoffice/lib:/var/lib/onlyoffice
      - ./onlyoffice/db:/var/lib/postgresql
    depends_on:
      - redis

  db:
    container_name: ncdb
    image: mariadb:latest
    restart: unless-stopped
    environment:
      - MYSQL_DATABASE=${NC_DB}
      - MYSQL_USER=${NC_DB_USER}
      - MYSQL_PASSWORD=${NC_DB_PWD}
      - 'MYSQL_ROOT_PASSWORD=${NC_DB_PWD}'
    volumes:
      - './media/ncconfigs/mariadb:/var/lib/mysql'

  redis:
    container_name: ncredis
    image: redis
    restart: unless-stopped
    command: redis-server --requirepass ${NC_REDIS_PWD}

networks:
  default:
    name: nextcloud
    driver: bridge
